MedioClinic/Models/InlineEditors/ImageUploader/ImageUploaderEditorViewModel.cs
using CMS.DocumentEngine;

namespace MedioClinic.Models.InlineEditors.ImageUploader
{
    public class ImageUploaderEditorViewModel : InlineEditorViewModel
    {
        public DocumentAttachment Image { get; set; }
    }
}

MedioClinic/Models/InlineEditors/InlineEditorViewModel.cs
namespace MedioClinic.Models.InlineEditors
{
    public abstract class InlineEditorViewModel
    {
        public string PropertyName { get; set; }
    }
}

MedioClinic/Models/InlineEditors/Slideshow/SlideshowEditorViewModel.cs
using System.Collections.Generic;
using CMS.DocumentEngine;

namespace MedioClinic.Models.InlineEditors.Slideshow
{
    public class SlideshowEditorViewModel : InlineEditorViewModel
    {
        public IEnumerable<DocumentAttachment> Images { get; set; }
        public string SwiperId { get; set; }
        public bool EnforceDimensions { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }
}

MedioClinic/Models/InlineEditors/TextEditor/TextEditorViewModel.cs
namespace MedioClinic.Models.InlineEditors.TextEditor
{
    public class TextEditorViewModel : InlineEditorViewModel
    {
        public string Text { get; set; }
    }
}

MedioClinic/Controllers/InlineEditors/ImageUploaderController.cs
using System;
using System.Web;
using System.Web.Mvc;
using MedioClinic.Utils;

namespace MedioClinic.Controllers.InlineEditors
{
    public class ImageUploaderController : Controller
    {
        protected string TempPath => $"{Server.MapPath(@"~\")}App_Data\\Temp\\ImageUploaderEditor";

        protected IFileManagementHelper FileManagementHelper { get; }

        protected IErrorHelper ErrorHelper { get; }

        public ImageUploaderController(IFileManagementHelper fileManagementHelper, IErrorHelper errorHandler)
        {
            FileManagementHelper = fileManagementHelper ?? throw new ArgumentNullException(nameof(fileManagementHelper));
            ErrorHelper = errorHandler ?? throw new ArgumentNullException(nameof(errorHandler));
        }

        // POST: ImageUploader/Upload/[pageId]
        [HttpPost]
        public ActionResult Upload(int pageId)
        {
            ErrorHelper.CheckEditMode(HttpContext, nameof(ImageUploaderController.Upload));
            var page = FileManagementHelper.GetPage(pageId);
            var imageGuid = Guid.Empty;

            if (Request.Files[0] is HttpPostedFileWrapper file && file != null)
            {
                try
                {
                    imageGuid = FileManagementHelper.AddUnsortedAttachment(page, TempPath, file);
                }
                catch (Exception ex)
                {
                    return ErrorHelper.HandleException(
                        nameof(ImageUploaderController),
                        nameof(Upload),
                        ex,
                        ErrorHelper.UnprocessableStatusCode);
                }

                return Json(new { guid = imageGuid });
            }

            return new HttpStatusCodeResult(ErrorHelper.UnprocessableStatusCode);
        }
    }
}

MedioClinic/Views/Shared/InlineEditors/_ImageUploaderEditor.cshtml
@using MedioClinic.Extensions
@model MedioClinic.Models.InlineEditors.ImageUploader.ImageUploaderEditorViewModel

@{
    string GetContainerClass() => Model.Image != null ? "kn-image-uploader-container" : "kn-image-uploader-empty-container";

    // Gets the URL to the ImageUploaderController's action.
    HtmlString GetActionUrl()
    {
        return Url.Kentico().AuthenticateUrl(Url.Action("Upload", "ImageUploader", new
        {
            pageId = Context.Kentico().PageBuilder().PageIdentifier
        }), false);
    }
}



@using (Html.Kentico().BeginInlineEditor("image-uploader-editor", Model.PropertyName,
new
{
    @class = "kn-image-uploader-editor",
    data_upload_url = GetActionUrl().ToString()
}))
{
<div class="@GetContainerClass()">
    <div class="dz-uploader">
        <div class="dz-message top">
            @Html.Raw(Html.Localize("InlineEditors.Dropzone.DropText"))
        </div>
    </div>
</div>
}

MedioClinic/Views/Shared/InlineEditors/_SlideshowEditor.cshtml
@using MedioClinic.Models.InlineEditors
@model MedioClinic.Models.InlineEditors.Slideshow.SlideshowEditorViewModel

@{
    // Gets the URL to the SlideshowManagementController's action.
    HtmlString GetActionUrl(string action)
    {
        return Url.Kentico().AuthenticateUrl(Url.Action(action, "SlideshowManagement", new
        {
            pageId = Context.Kentico().PageBuilder().PageIdentifier
        }), false);
    }

    string SerializeGuids(IEnumerable<Guid> guids) =>
        string.Concat(guids.Select(guid => guid.ToString() + ";"));
}

@using (Html.Kentico().BeginInlineEditor("slideshow-editor", Model.PropertyName,
    new
    {
        @class = "kn-slideshow-editor",
        data_swiper_guid = Model.SwiperId,
        data_image_guids = SerializeGuids(Model.Images.Select(image => image.AttachmentGUID)),
        data_upload_url = GetActionUrl("Upload").ToString(),
        data_delete_url = GetActionUrl("Delete").ToString(),
    }))
{
    <ul class="kn-slideshow-buttons">
        <li>
            <button class="kn-swiper-plus">+</button>
        </li>
        <li>
            <button class="kn-swiper-minus">-</button>
        </li>
    </ul>
}

MedioClinic/Views/Shared/InlineEditors/_TextEditor.cshtml
@model MedioClinic.Models.InlineEditors.TextEditor.TextEditorViewModel

@using (Html.Kentico().BeginInlineEditor("text-editor", Model.PropertyName,
    new
    {
        @class = "text-editor"
    }))
{
    @Html.Raw(Model.Text)
}